dist: xenial

language: php

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

addons:
  postgresql: "9.6"

matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: SYMFONY_VERSION="^3.4"
    - php: 7.2
      env: SYMFONY_VERSION="^4.4"
    - php: 7.2
      env: EXTRA_PACKAGES="doctrine/phpcr-bundle:^2.0 doctrine/phpcr-odm:^1.3 jackalope/jackalope-doctrine-dbal:^1.5"
    - php: 7.3
      env: SYMFONY_VERSION="^4.4"
    - php: 7.3 
      env: SYMFONY_VERSION="^5.0" 
    - php: 8.0
      env: SYMFONY_VERSION="^4.4"
    - php: 8.0
      env: SYMFONY_VERSION="^5.0" 
  allow_failures:
    - php: 7.2
      env: EXTRA_PACKAGES="doctrine/phpcr-bundle:^2.0 doctrine/phpcr-odm:^1.3 jackalope/jackalope-doctrine-dbal:^1.5"
  fast_finish: true

before_install:
  - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/framework-bundle=$SYMFONY_VERSION; fi
  - if [ "$EXTRA_PACKAGES" != "" ]; then composer require --no-update $EXTRA_PACKAGES; fi

install:
  # use "update" instead of "install" since it allows using the "--prefer-lowest" option
  - composer update $COMPOSER_FLAGS

# In phpunit.xml.dist, tests annotated with "@group mysql" are excluded,
# revert this.
# Run tests twice to ensure that tests are idempotent even if database caching is enabled
script:
  - php ./vendor/bin/phpunit --exclude-group ""
  - php ./vendor/bin/phpunit --exclude-group ""
